---
title: "Sample overview"
author: X Shen  
date: "\n`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

```{r library,echo=F}
library(dplyr)
library(data.table)
library(readr)
library(pbapply)
library(ggplot2)
library(knitr)
library(kableExtra)
library(here)
library(ggpubr)

f.dat_dir = 'data/'
f.PRS = 'data/PRS_all.rds'
f.model = 'data/fields_toi.rds'
```

```{r rendering docs, eval=F,echo=F}
#render('scripts/phewas/SUMMARY/summary.sample_n_phenotype.Rmd',output_dir='docs/',output_file='summary.pt_0.1.md')
```

### Sample description

```{r sample description, echo=F,warning=FALSE}
fs = list.files(path=f.dat_dir,pattern = 'dat.', full.names = T)%>% 
  (function(x) x[grep('chunk.rds',x)])

PRS=readRDS(here::here(f.PRS))

phewas.dat = fs %>% as.list %>% lapply(.,FUN=function(x) readRDS(here::here(x))) %>% 
  Reduce(function(dtf1,dtf2) merge(dtf1,dtf2,by="f.eid",all=T), .) %>% 
  left_join(PRS,.,by='f.eid') %>% 
  as.data.frame

covs = phewas.dat %>% 
  select(f.eid,starts_with('cov')) %>% 
  mutate(cov.sex_instance2=ifelse(!is.na(cov.age_instance2),cov.sex,NA),
         cov.sex_mhq=ifelse(!is.na(cov.age_mhq),cov.sex,NA),
         cov.ageGap_instance2=cov.age_instance2-cov.age_instance0,
         cov.ageGap_mhq=cov.age_mhq-cov.age_instance0)

age.mean = covs %>% 
  select(starts_with('cov.age_')) %>% 
  colMeans(.,na.rm = T) 
age.sd =  covs %>% 
  select(starts_with('cov.age_')) %>% 
  apply(.,MARGIN = 2,FUN = sd,na.rm = T) 

sex.percentage = covs %>% 
  select(starts_with('cov.sex')) %>% 
  sapply(.,as.numeric) %>%
  as.data.frame %>% 
  sapply(.,FUN = function(x) sum(x==2,na.rm=T)/sum(!is.na(x)))

ageGap.mean = covs %>%  
  select(starts_with('cov.ageGap_')) %>% 
  colMeans(.,na.rm = T) 
ageGap.sd =  covs %>% 
  select(starts_with('cov.ageGap_')) %>% 
  apply(.,MARGIN = 2,FUN = sd,na.rm = T) 

summary.table.sample = data.frame(Assessment = c('Baseline','MRI','Online'),
                           `Age` = paste0(round(age.mean,2),' (',round(age.sd,2),')'),
                           `Sex` = sprintf("%1.2f%%", 100*sex.percentage),
                           `Age gap` = c('--',paste0(round(ageGap.mean,2),' (',
                                             round(ageGap.sd,2),')')))

summary.table.sample %>%
  kbl() %>%
  kable_material(c("striped", "hover"))
```

### Phenotypes

```{r summarise phenotypes, warning=F,echo=F}
sum_N_cat <- function(x,cate,ref){
  ref.block = ref %>% filter(.$category==cate)
  cats = ref.block$Category %>% unique %>% .[!is.na(.)] %>% paste0(.,collapse = ',') 
  
  x.block = x %>% .[,colnames(.) %in% ref.block$field_tag]
  
  Nmin = colSums(!is.na(x.block)) %>% min
  Nmax = colSums(!is.na(x.block)) %>% max
  Nmedian = colSums(!is.na(x.block)) %>% median
  Nmean = colSums(!is.na(x.block)) %>% mean
  
  output = data.frame(Category=cate,Category.ID=cats,
                      Nmin=Nmin,Nmax=Nmax,Nmedian=Nmedian)
  return(output)
}

ls.models = readRDS(f.model)
ls.models = ls.models %>% .[!.$field_tag %in% c('f.6153','f.6177','f.2375','f.2385','f.2395','f.2405','f.2674','f.2684','f.2694','f.2704','f.2714','f.2724','f.2734','f.2744','f.2754','f.2764','f.2774','f.2784','f.2794','f.2804','f.2814','f.2824','f.2834','f.3140','f.3536','f.3581','f.3591','f.3700','f.3710','f.3720','f.3829','f.3839','f.3849','f.3872','f.3882','f.4041','f.3546'),]

summary.table.phenotype = ls.models$category %>% unique %>% as.list %>% 
  pblapply(.,FUN=sum_N_cat,x=phewas.dat,ref=ls.models) %>% 
  bind_rows

```

