name: mdd3
channels:
  - conda-forge
  - bioconda
dependencies:
  - python =3.7
  - bioconda::snakemake-minimal =5.20.1
  - dropbox
  - r-base =4.0.2
  - r-essentials
  - bioconductor-rtracklayer =1.48.0
