library(dplyr)
library(data.table)
library(readr)
library(TwoSampleMR)
library(pbapply)
library(optparse)


# Load arguments ----------------------------------------------------------
# Environment: R 3.6.1
args <- commandArgs(trailingOnly = FALSE)

parse <- OptionParser()

option_list <- list(
   make_option('--exposure', type='character', help="Intermediate files for exposure data", action='store'),
   make_option('--outcomeName', default='MDD', type='character', help='Name of outcome phenotype', action='store'),
   make_option('--summout', type='character', help="Summary stats for outcome", action='store'),
   make_option('--interout', type='character', help='Folder for intermediate files generated by processing outcome data', action='store')
)

args = commandArgs(trailingOnly=TRUE)

opt <- parse_args(OptionParser(option_list=option_list), args=args)
exposure.path=opt$exposure
summ.outcome=opt$summout
outcome.name=opt$outcomeName
output.path=opt$interout


# Basic settings ----------------------------------------------------------

dir.create(file.path(output.path), showWarnings = FALSE)

# Load outcome data -------------------------------------------------------

outcome.summstats=read_tsv(summ.outcome) %>%
   mutate(Beta=log(OR),N=2*Neff_half) %>% 
   select(SNP,A1,A2,Beta,SE,P,Direction,af=FRQ_A_235237,CHR,BP,N) 


# Process outcome data ----------------------------------------------------

process_outcome <- function(f.exposure,dat.outcome.full){

   ls.processed = list.files(path = output.path, pattern = '.outcome_dat',full.names = T) %>% 
      basename %>% 
      gsub('.outcome_dat','',.,fixed = T) %>% 
      gsub(paste0('.',outcome.name),'',.,fixed = T)
   ls.running = read_tsv('data/MR/running_mdd_outcome',col_names=F) %>% as.data.frame %>% 
      .$X1 %>% as.character %>% as.vector
   ls.avoid = c(ls.processed,ls.running)
   
   n.exposure = f.exposure %>% basename %>% gsub('.exposure_dat','',.,fixed = T)
   if(sum(n.exposure %in% ls.avoid)==0){
      
      traitA=n.exposure
      traitB=outcome.name
      system(paste0('echo ',n.exposure,' >> data/MR/running_mdd_outcome'))
      
      ## exposure dat
      exposure.dat=read_tsv(f.exposure) %>% as.data.frame
      
      ## outcome dat
      outcome_match=outcome.summstats[outcome.summstats$SNP %in% exposure.dat$SNP,] %>%
         dplyr::select(SNP,effect_allele=A1,other_allele=A2,
                       eaf=af,beta=Beta,se=SE,pval=P,samplesize=N) %>% 
         mutate(Phenotype=traitB)

      outcome_dat = format_data(outcome_match, type="outcome")
      
      write_tsv(outcome_dat,
                  paste0(output.path,'/',traitA,'.',traitB,".outcome_dat"))
   }
   gc()
}

system('touch data/MR/running_mdd_outcome')
ls.exposure.filename = list.files(path = exposure.path, pattern = '.exposure_dat',full.names=T)
ls.rm = list.files(path = output.path, pattern = '.outcome_dat',full.names = T) %>% 
   basename %>% 
   gsub(paste0('.',outcome.name,'.outcome_dat'),'.exposure_dat',.,fixed = T) %>% 
   paste0(.,collapse = '|')
if(ls.rm!=''){
   ls.exposure.filename %>% .[!grepl(ls.rm,.)] %>% as.list %>% 
      pblapply(.,process_outcome,dat.outcome.full=outcome.summstats)   
}else{
   ls.exposure.filename %>%  as.list %>% 
      pblapply(.,process_outcome,dat.outcome.full=outcome.summstats) 
}




rm(list=ls())