channels:
  - conda-forge
  - bioconda
dependencies:
  - dropbox
  - r-base =4.0.5
  - r-essentials
  - bioconductor-rtracklayer =1.48.0
  - r-dplyr
  - r-tidyr
  - r-stringr
  - r-gdata
  - r-psych
  - r-glmnet
  - r-remotes
  - r-nloptr
  - r-minqa
  - r-rcppeigen
  - gmp
  - plink =1.90b6.21
  - bitarray
  - cmake
  
