---
title: "Phenotypes used in the PRS PheWAS"
author: X Shen  
date: "\n`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
always_allow_html: true
---

```{r library,echo=F,warning=F,error=F,message=F}
library(dplyr)
library(tidyverse)
library(data.table)
library(readr)
library(pbapply)
library(ggplot2)
library(knitr)
library(kableExtra)
library(here)
library(ggpubr)
```

```{r,echo=F,warning=F,message=F}

f.dic_dir = 'results/phewas/data_dictionary/fields.final.brain_imaging_QC_cov_phenotype.txt'

d.path = f.dic_dir %>% strsplit(.,'/') %>% unlist %>% 
  .[1:(length(.)-1)] %>% 
  paste0(.,collapse = '/')

fields.all = list.files(here::here(d.path),pattern='^fields.final',full.names = T,include.dirs = T) %>% 
  as.list %>%
  lapply(.,FUN=function(x){ fread(here::here(x),stringsAsFactors=F,header=T,sep='\t',quote="")}) %>%
  lapply(as.data.frame) %>% 
  lapply(mutate,field_used=as.character(field_used),FieldID=as.character(FieldID)) %>% 
  Reduce(function(dtf1,dtf2) bind_rows(dtf1,dtf2[,colnames(dtf1)]), .)

fields.show = fields.all %>% 
  dplyr::select(Category_name=category,FieldID,Field,Participants,Link,CategoryID=Category,Field_used=field_used)
  

```


```{r,echo=F,message=F,warning=F}
fields.show %>% 
as_tibble %>% 
  kable('html',escape=T) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%  
   column_spec(3, width_min = "1.8in")
  # column_spec(7, border_right=T) %>% 
  # column_spec(10, border_right=T) %>% 
  # column_spec(12, width_min = "3.5in")

```

