---
title: "PheWAS"
author: X Shen  
date: "\n`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

This page describes the use of scripts in the *scripts/phewa*s folder.

All the rules are included in the rules/phewas.smk file and they are loaded in the Snakemake file.

In general, the rules consist of four modules: PRS calculation, phenotype preparation, analysis and visualisation. Each of the module is described in detail below.

------------------------------------------------------------------------

## PRS calculation

All rules and scripts can be found in the rules/phewas.smk file, PRS section.

Sumstats:

The '*daner_pgc_mdd_noUKBB_eur_hg19_v3.49.24.05.rp.gz*' sumstats was used. QC for sumstats are (in *scripts/phewas/PREP.PRS/PREP.sumstats.R*):

------------------------------------------------------------------------

## Phenotype preparation

### Modalities require extra processing

#### Imaging

Phenotypes generated under the same type but using different atlases, only one atlas was included. See phenotypes in results/phewas/data_dictionary/fields.brain_imaging_QC_cov.txt for all the phenotypes included.

To minimise unnecessary multiple comparisons, mean value for measures for bilateral structural/functional measures were generated to replace separate values for each hemisphere.

In rule 'chunk_brain_imaging':

> **inputs:**
>
> -   data/Data_Dictionary_Showcase.csv (data dictionary from [UKB datashowcase](https://biobank.ctsu.ox.ac.uk/~bbdatan/Data_Dictionary_Showcase.csv))
>
> -   results/phewas/data_dictionary/fields.imaging_phenotype.txt (selected and manually QC'ed)
>
> -   data/2021-04-phenotypes-ukb44797/Imaging.rds (rds file for brain, heart etc [IDPs](https://biobank.ndph.ox.ac.uk/showcase/label.cgi?id=100003) from UKB)
>
> -   results/phewas/data_dictionary/fields.brain_imaging_QC_cov.txt (selected and manually QC'ed)
>
> -   data/2021-04-phenotypes-ukb44797/Recruitment.rds (rds for [recruitment info](https://biobank.ndph.ox.ac.uk/showcase/label.cgi?id=100021) from UKB)
>
> **outputs:**
>
> -   data/dat.imaging_chunk.rds
>
> -   results/phewas/data_dictionary/fields.final.brain_imaging_QC_cov_phenotype.txt
>
> **Shell command:**
>
> Rscript scripts/phewas/PREP.phenotype_ukb/process_BrainImaging_2.R {input} {output}

### Cognition

### Loose phenotypes
