library(dplyr)
library(data.table)
library(readr)
library(TwoSampleMR)
library(pbapply)
library(optparse)


# Load arguments ----------------------------------------------------------
# Environment: R 3.6.1
args <- commandArgs(trailingOnly = FALSE)

parse <- OptionParser()

option_list <- list(
   make_option('--exposureSNP', type='character', help="SNPs included in the final exposure data", action='store'),
   make_option('--outcomeName', default='MDD', type='character', help='Name of outcome phenotype', action='store'),
   make_option('--summout', type='character', help="Summary stats for outcome", action='store'),
   make_option('--interout', type='character', help='Folder for intermediate files generated by processing outcome data', action='store')
)

args = commandArgs(trailingOnly=TRUE)

opt <- parse_args(OptionParser(option_list=option_list), args=args)
ls.snp_include=opt$exposureSNP
summ.outcome=opt$summout
outcome.name=opt$outcomeName
output.path=opt$interout


# Basic settings ----------------------------------------------------------

dir.create(file.path(output.path), showWarnings = FALSE)

# Load outcome data -------------------------------------------------------

outcome.summstats=read_tsv(summ.outcome) %>%
   mutate(Beta=log(OR),N=2*Neff_half) %>% 
   select(SNP,A1,A2,Beta,SE,P,Direction,af=FRQ_A_470188,CHR,BP,N) 


# Process outcome data ----------------------------------------------------

traitB=outcome.name

## exposure dat
exposure.snps=read_tsv(ls.snp_include,col_names=F) %>% {.$X1} 

## outcome dat
outcome_match=outcome.summstats[outcome.summstats$SNP %in% exposure.snps,] %>%
   dplyr::select(SNP,effect_allele=A1,other_allele=A2,
                 eaf=af,beta=Beta,se=SE,pval=P,samplesize=N) %>% 
   mutate(Phenotype=traitB)

outcome_dat = format_data(outcome_match, type="outcome")

write_tsv(outcome_dat,
            paste0(output.path,'/multivar.',traitB,".outcome_dat"))

gc()

rm(list=ls())